$(document).ready(function(){
	$('.dropdown-toggle').mouseover(function(){
		$('.megamenu').css('display','block');
	});
	$('.megamenu').mouseover(function(){
		$('.megamenu').css('display','block');
	});
	$('.megamenu').mouseout(function(){
		$('.megamenu').css('display','none');
	});
	//allcourese
	$('.all-courses').mouseover(function(){				
		$(".content:has(.overlay)").css('backgroundColor','#50C6D1'),
		$('.overlay').css('backgroundColor','#50C6D1'),
		$('.all-courses').css('transform','scale(1.1)');
	});
	$('.all-courses').mouseout(function(){
		$(".content:has(.overlay)").css('backgroundColor','rgba(128,128,128,1)'),
		$('.overlay').css('backgroundColor','rgba(128,128,128,1)'),
		$('.all-courses').css('transform','scale(1.0)');
	});
	//acounting
	$('.keepbooking').mouseover(function(){				
		$(this).css("backgroundColor","#50C6D1"),
		$(this).css('transform','scale(1.1)');
	});
	$('.keepbooking').mouseout(function(){
		$(this).css('backgroundColor','rgba(128,128,128,1)'),
		$(this).css('transform','scale(1.0)');
		;
	});
	//code
	$('.code').mouseover(function(){				
		$(this).css("backgroundColor","#50C6D1"),
		$(this).css('transform','scale(1.1)');
	});
	$('.code').mouseout(function(){
		$(this).css('backgroundColor','rgba(128,128,128,1)'),
		$(this).css('transform','scale(1.0)');
		;
	});
	//english
	$('.en').mouseover(function(){				
		$(this).css("backgroundColor","#50C6D1"),
		$(this).css('transform','scale(1.1)')
	});
	$('.en').mouseout(function(){
		$(this).css('backgroundColor','rgba(128,128,128,1)'),
		$(this).css('transform','scale(1.0)');
		;
	});
	//sale
	$('.sale').mouseover(function(){				
		$(this).css("backgroundColor","#50C6D1"),
		$(this).css('transform','scale(1.1)');
	});
	$('.sale').mouseout(function(){
		$(this).css('backgroundColor','rgba(128,128,128,1)'),
		$(this).css('transform','scale(1.0)');
	});
	//digital
	$('.digital').mouseover(function(){				
		$(this).css("backgroundColor","#50C6D1"),
		$(this).css('transform','scale(1.1)');
	});
	$('.digital').mouseout(function(){
		$(this).css('backgroundColor','rgba(128,128,128,1)'),
		$(this).css('transform','scale(1.0)');		
	});
	//founded
	$('.founded').mouseover(function(){				
		$(this).css("backgroundColor","#50C6D1"),
		$(this).css('transform','scale(1.1)');
	});
	$('.founded').mouseout(function(){
		$(this).css('backgroundColor','rgba(128,128,128,1)'),
		$(this).css('transform','scale(1.0)');		
	});
	//tạo popup khi màn hình nhỏ hơn 1000px
	$('.navbar-toggle').click(function(){
		
		$('.toogle-box').toggle();
	});
	//modal login
	$('#link_login').click(function(){
		$("#login").modal('show');
	});
	$('.login').click(function(){
		$("#login").modal(),
		$('.toogle-box').css('display','none');
	});
	//modal sign up
	$('#link_signup').click(function(){
		$("#signup").modal('show');
	});
	$('.sigup').click(function(){
		$("#signup").modal(),
		$('.toogle-box').css('display','none');
	});
});